/*
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * OpenAPI spec version: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.zebrunner.carina.bitrise.client.model;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;


/**
 * NullsString
 */



public class NullsString {
  @SerializedName("string")
  private String string = null;

  @SerializedName("valid")
  private Boolean valid = null;

  public NullsString string(String string) {
    this.string = string;
    return this;
  }

   /**
   * Get string
   * @return string
  **/
  
  public String getString() {
    return string;
  }

  public void setString(String string) {
    this.string = string;
  }

  public NullsString valid(Boolean valid) {
    this.valid = valid;
    return this;
  }

   /**
   * Valid is true if String is not NULL
   * @return valid
  **/
  
  public Boolean isValid() {
    return valid;
  }

  public void setValid(Boolean valid) {
    this.valid = valid;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NullsString nullsString = (NullsString) o;
    return Objects.equals(this.string, nullsString.string) &&
        Objects.equals(this.valid, nullsString.valid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(string, valid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NullsString {\n");
    
    sb.append("    string: ").append(toIndentedString(string)).append("\n");
    sb.append("    valid: ").append(toIndentedString(valid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
