/*
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * OpenAPI spec version: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.zebrunner.carina.bitrise.client.model;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;


/**
 * V0ActivityEventResponseItemModel
 */



public class V0ActivityEventResponseItemModel {
  @SerializedName("created_at")
  private String createdAt = null;

  @SerializedName("description")
  private NullsString description = null;

  @SerializedName("event_icon")
  private NullsString eventIcon = null;

  @SerializedName("event_stype")
  private NullsString eventStype = null;

  @SerializedName("repository_avatar_icon_url")
  private String repositoryAvatarIconUrl = null;

  @SerializedName("repository_title")
  private String repositoryTitle = null;

  @SerializedName("slug")
  private String slug = null;

  @SerializedName("target_path_string")
  private NullsString targetPathString = null;

  @SerializedName("title")
  private NullsString title = null;

  public V0ActivityEventResponseItemModel createdAt(String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/

  public String getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }

  public V0ActivityEventResponseItemModel description(NullsString description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/

  public NullsString getDescription() {
    return description;
  }

  public void setDescription(NullsString description) {
    this.description = description;
  }

  public V0ActivityEventResponseItemModel eventIcon(NullsString eventIcon) {
    this.eventIcon = eventIcon;
    return this;
  }

   /**
   * Get eventIcon
   * @return eventIcon
  **/

  public NullsString getEventIcon() {
    return eventIcon;
  }

  public void setEventIcon(NullsString eventIcon) {
    this.eventIcon = eventIcon;
  }

  public V0ActivityEventResponseItemModel eventStype(NullsString eventStype) {
    this.eventStype = eventStype;
    return this;
  }

   /**
   * Get eventStype
   * @return eventStype
  **/

  public NullsString getEventStype() {
    return eventStype;
  }

  public void setEventStype(NullsString eventStype) {
    this.eventStype = eventStype;
  }

  public V0ActivityEventResponseItemModel repositoryAvatarIconUrl(String repositoryAvatarIconUrl) {
    this.repositoryAvatarIconUrl = repositoryAvatarIconUrl;
    return this;
  }

   /**
   * Get repositoryAvatarIconUrl
   * @return repositoryAvatarIconUrl
  **/

  public String getRepositoryAvatarIconUrl() {
    return repositoryAvatarIconUrl;
  }

  public void setRepositoryAvatarIconUrl(String repositoryAvatarIconUrl) {
    this.repositoryAvatarIconUrl = repositoryAvatarIconUrl;
  }

  public V0ActivityEventResponseItemModel repositoryTitle(String repositoryTitle) {
    this.repositoryTitle = repositoryTitle;
    return this;
  }

   /**
   * Get repositoryTitle
   * @return repositoryTitle
  **/

  public String getRepositoryTitle() {
    return repositoryTitle;
  }

  public void setRepositoryTitle(String repositoryTitle) {
    this.repositoryTitle = repositoryTitle;
  }

  public V0ActivityEventResponseItemModel slug(String slug) {
    this.slug = slug;
    return this;
  }

   /**
   * Get slug
   * @return slug
  **/

  public String getSlug() {
    return slug;
  }

  public void setSlug(String slug) {
    this.slug = slug;
  }

  public V0ActivityEventResponseItemModel targetPathString(NullsString targetPathString) {
    this.targetPathString = targetPathString;
    return this;
  }

   /**
   * Get targetPathString
   * @return targetPathString
  **/

  public NullsString getTargetPathString() {
    return targetPathString;
  }

  public void setTargetPathString(NullsString targetPathString) {
    this.targetPathString = targetPathString;
  }

  public V0ActivityEventResponseItemModel title(NullsString title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/

  public NullsString getTitle() {
    return title;
  }

  public void setTitle(NullsString title) {
    this.title = title;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V0ActivityEventResponseItemModel v0ActivityEventResponseItemModel = (V0ActivityEventResponseItemModel) o;
    return Objects.equals(this.createdAt, v0ActivityEventResponseItemModel.createdAt) &&
        Objects.equals(this.description, v0ActivityEventResponseItemModel.description) &&
        Objects.equals(this.eventIcon, v0ActivityEventResponseItemModel.eventIcon) &&
        Objects.equals(this.eventStype, v0ActivityEventResponseItemModel.eventStype) &&
        Objects.equals(this.repositoryAvatarIconUrl, v0ActivityEventResponseItemModel.repositoryAvatarIconUrl) &&
        Objects.equals(this.repositoryTitle, v0ActivityEventResponseItemModel.repositoryTitle) &&
        Objects.equals(this.slug, v0ActivityEventResponseItemModel.slug) &&
        Objects.equals(this.targetPathString, v0ActivityEventResponseItemModel.targetPathString) &&
        Objects.equals(this.title, v0ActivityEventResponseItemModel.title);
  }

  @Override
  public int hashCode() {
    return Objects.hash(createdAt, description, eventIcon, eventStype, repositoryAvatarIconUrl, repositoryTitle, slug, targetPathString, title);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V0ActivityEventResponseItemModel {\n");
    
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    eventIcon: ").append(toIndentedString(eventIcon)).append("\n");
    sb.append("    eventStype: ").append(toIndentedString(eventStype)).append("\n");
    sb.append("    repositoryAvatarIconUrl: ").append(toIndentedString(repositoryAvatarIconUrl)).append("\n");
    sb.append("    repositoryTitle: ").append(toIndentedString(repositoryTitle)).append("\n");
    sb.append("    slug: ").append(toIndentedString(slug)).append("\n");
    sb.append("    targetPathString: ").append(toIndentedString(targetPathString)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
