/*
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * OpenAPI spec version: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.zebrunner.carina.bitrise.client.model;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * V0AppAddOnResponseItemModel
 */

public class V0AppAddOnResponseItemModel {
    @SerializedName("description")
    private String description = null;

    @SerializedName("documentation_url")
    private String documentationUrl = null;

    @SerializedName("has_ui")
    private Boolean hasUi = null;

    @SerializedName("icon")
    private String icon = null;

    @SerializedName("id")
    private String id = null;

    @SerializedName("is_beta")
    private Boolean isBeta = null;

    @SerializedName("is_enabled")
    private Boolean isEnabled = null;

    @SerializedName("login_url")
    private String loginUrl = null;

    @SerializedName("plan")
    private AddonsPlan plan = null;

    @SerializedName("scopes")
    private List<String> scopes = null;

    @SerializedName("setup_guide")
    private AddonsSetupGuide setupGuide = null;

    @SerializedName("summary")
    private String summary = null;

    @SerializedName("terms_url")
    private String termsUrl = null;

    @SerializedName("title")
    private String title = null;

    public V0AppAddOnResponseItemModel description(String description) {
        this.description = description;
        return this;
    }

    /**
     * Get description
     *
     * @return description
     **/

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public V0AppAddOnResponseItemModel documentationUrl(String documentationUrl) {
        this.documentationUrl = documentationUrl;
        return this;
    }

    /**
     * Get documentationUrl
     *
     * @return documentationUrl
     **/

    public String getDocumentationUrl() {
        return documentationUrl;
    }

    public void setDocumentationUrl(String documentationUrl) {
        this.documentationUrl = documentationUrl;
    }

    public V0AppAddOnResponseItemModel hasUi(Boolean hasUi) {
        this.hasUi = hasUi;
        return this;
    }

    /**
     * Get hasUi
     *
     * @return hasUi
     **/

    public Boolean isHasUi() {
        return hasUi;
    }

    public void setHasUi(Boolean hasUi) {
        this.hasUi = hasUi;
    }

    public V0AppAddOnResponseItemModel icon(String icon) {
        this.icon = icon;
        return this;
    }

    /**
     * Get icon
     *
     * @return icon
     **/

    public String getIcon() {
        return icon;
    }

    public void setIcon(String icon) {
        this.icon = icon;
    }

    public V0AppAddOnResponseItemModel id(String id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     *
     * @return id
     **/

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public V0AppAddOnResponseItemModel isBeta(Boolean isBeta) {
        this.isBeta = isBeta;
        return this;
    }

    /**
     * Get isBeta
     *
     * @return isBeta
     **/

    public Boolean isIsBeta() {
        return isBeta;
    }

    public void setIsBeta(Boolean isBeta) {
        this.isBeta = isBeta;
    }

    public V0AppAddOnResponseItemModel isEnabled(Boolean isEnabled) {
        this.isEnabled = isEnabled;
        return this;
    }

    /**
     * Get isEnabled
     *
     * @return isEnabled
     **/

    public Boolean isIsEnabled() {
        return isEnabled;
    }

    public void setIsEnabled(Boolean isEnabled) {
        this.isEnabled = isEnabled;
    }

    public V0AppAddOnResponseItemModel loginUrl(String loginUrl) {
        this.loginUrl = loginUrl;
        return this;
    }

    /**
     * Get loginUrl
     *
     * @return loginUrl
     **/

    public String getLoginUrl() {
        return loginUrl;
    }

    public void setLoginUrl(String loginUrl) {
        this.loginUrl = loginUrl;
    }

    public V0AppAddOnResponseItemModel plan(AddonsPlan plan) {
        this.plan = plan;
        return this;
    }

    /**
     * Get plan
     *
     * @return plan
     **/

    public AddonsPlan getPlan() {
        return plan;
    }

    public void setPlan(AddonsPlan plan) {
        this.plan = plan;
    }

    public V0AppAddOnResponseItemModel scopes(List<String> scopes) {
        this.scopes = scopes;
        return this;
    }

    public V0AppAddOnResponseItemModel addScopesItem(String scopesItem) {
        if (this.scopes == null) {
            this.scopes = new ArrayList<String>();
        }
        this.scopes.add(scopesItem);
        return this;
    }

    /**
     * Get scopes
     *
     * @return scopes
     **/

    public List<String> getScopes() {
        return scopes;
    }

    public void setScopes(List<String> scopes) {
        this.scopes = scopes;
    }

    public V0AppAddOnResponseItemModel setupGuide(AddonsSetupGuide setupGuide) {
        this.setupGuide = setupGuide;
        return this;
    }

    /**
     * Get setupGuide
     *
     * @return setupGuide
     **/

    public AddonsSetupGuide getSetupGuide() {
        return setupGuide;
    }

    public void setSetupGuide(AddonsSetupGuide setupGuide) {
        this.setupGuide = setupGuide;
    }

    public V0AppAddOnResponseItemModel summary(String summary) {
        this.summary = summary;
        return this;
    }

    /**
     * Get summary
     *
     * @return summary
     **/

    public String getSummary() {
        return summary;
    }

    public void setSummary(String summary) {
        this.summary = summary;
    }

    public V0AppAddOnResponseItemModel termsUrl(String termsUrl) {
        this.termsUrl = termsUrl;
        return this;
    }

    /**
     * Get termsUrl
     *
     * @return termsUrl
     **/

    public String getTermsUrl() {
        return termsUrl;
    }

    public void setTermsUrl(String termsUrl) {
        this.termsUrl = termsUrl;
    }

    public V0AppAddOnResponseItemModel title(String title) {
        this.title = title;
        return this;
    }

    /**
     * Get title
     *
     * @return title
     **/

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V0AppAddOnResponseItemModel v0AppAddOnResponseItemModel = (V0AppAddOnResponseItemModel) o;
        return Objects.equals(this.description, v0AppAddOnResponseItemModel.description) &&
                Objects.equals(this.documentationUrl, v0AppAddOnResponseItemModel.documentationUrl) &&
                Objects.equals(this.hasUi, v0AppAddOnResponseItemModel.hasUi) &&
                Objects.equals(this.icon, v0AppAddOnResponseItemModel.icon) &&
                Objects.equals(this.id, v0AppAddOnResponseItemModel.id) &&
                Objects.equals(this.isBeta, v0AppAddOnResponseItemModel.isBeta) &&
                Objects.equals(this.isEnabled, v0AppAddOnResponseItemModel.isEnabled) &&
                Objects.equals(this.loginUrl, v0AppAddOnResponseItemModel.loginUrl) &&
                Objects.equals(this.plan, v0AppAddOnResponseItemModel.plan) &&
                Objects.equals(this.scopes, v0AppAddOnResponseItemModel.scopes) &&
                Objects.equals(this.setupGuide, v0AppAddOnResponseItemModel.setupGuide) &&
                Objects.equals(this.summary, v0AppAddOnResponseItemModel.summary) &&
                Objects.equals(this.termsUrl, v0AppAddOnResponseItemModel.termsUrl) &&
                Objects.equals(this.title, v0AppAddOnResponseItemModel.title);
    }

    @Override
    public int hashCode() {
        return Objects.hash(description, documentationUrl, hasUi, icon, id, isBeta, isEnabled, loginUrl, plan, scopes, setupGuide, summary, termsUrl,
                title);
    }

    @Override
    public String toString() {

        String sb = "class V0AppAddOnResponseItemModel {\n"
                + "    description: " + toIndentedString(description) + "\n"
                + "    documentationUrl: " + toIndentedString(documentationUrl) + "\n"
                + "    hasUi: " + toIndentedString(hasUi) + "\n"
                + "    icon: " + toIndentedString(icon) + "\n"
                + "    id: " + toIndentedString(id) + "\n"
                + "    isBeta: " + toIndentedString(isBeta) + "\n"
                + "    isEnabled: " + toIndentedString(isEnabled) + "\n"
                + "    loginUrl: " + toIndentedString(loginUrl) + "\n"
                + "    plan: " + toIndentedString(plan) + "\n"
                + "    scopes: " + toIndentedString(scopes) + "\n"
                + "    setupGuide: " + toIndentedString(setupGuide) + "\n"
                + "    summary: " + toIndentedString(summary) + "\n"
                + "    termsUrl: " + toIndentedString(termsUrl) + "\n"
                + "    title: " + toIndentedString(title) + "\n"
                + "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
