/*
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * OpenAPI spec version: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.zebrunner.carina.bitrise.client.model;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * V0AppWebhookUpdateParams
 */

public class V0AppWebhookUpdateParams {
    @SerializedName("events")
    private List<String> events = new ArrayList<String>();

    @SerializedName("headers")
    private List<Integer> headers = null;

    @SerializedName("url")
    private String url = null;

    public V0AppWebhookUpdateParams events(List<String> events) {
        this.events = events;
        return this;
    }

    public V0AppWebhookUpdateParams addEventsItem(String eventsItem) {
        this.events.add(eventsItem);
        return this;
    }

    /**
     * Get events
     *
     * @return events
     **/

    public List<String> getEvents() {
        return events;
    }

    public void setEvents(List<String> events) {
        this.events = events;
    }

    public V0AppWebhookUpdateParams headers(List<Integer> headers) {
        this.headers = headers;
        return this;
    }

    public V0AppWebhookUpdateParams addHeadersItem(Integer headersItem) {
        if (this.headers == null) {
            this.headers = new ArrayList<Integer>();
        }
        this.headers.add(headersItem);
        return this;
    }

    /**
     * Get headers
     *
     * @return headers
     **/

    public List<Integer> getHeaders() {
        return headers;
    }

    public void setHeaders(List<Integer> headers) {
        this.headers = headers;
    }

    public V0AppWebhookUpdateParams url(String url) {
        this.url = url;
        return this;
    }

    /**
     * Get url
     *
     * @return url
     **/

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V0AppWebhookUpdateParams v0AppWebhookUpdateParams = (V0AppWebhookUpdateParams) o;
        return Objects.equals(this.events, v0AppWebhookUpdateParams.events) &&
                Objects.equals(this.headers, v0AppWebhookUpdateParams.headers) &&
                Objects.equals(this.url, v0AppWebhookUpdateParams.url);
    }

    @Override
    public int hashCode() {
        return Objects.hash(events, headers, url);
    }

    @Override
    public String toString() {

        String sb = "class V0AppWebhookUpdateParams {\n"
                + "    events: " + toIndentedString(events) + "\n"
                + "    headers: " + toIndentedString(headers) + "\n"
                + "    url: " + toIndentedString(url) + "\n"
                + "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
