/*
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * OpenAPI spec version: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.zebrunner.carina.bitrise.client.model;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

/**
 * V0AppUpdateParams
 */

public class V0AppUpdateParams {
    @SerializedName("apple_credential_user_id")
    private Integer appleCredentialUserId = null;

    @SerializedName("apple_credential_user_slug")
    private String appleCredentialUserSlug = null;

    @SerializedName("default_branch")
    private String defaultBranch = null;

    @SerializedName("is_public")
    private Boolean isPublic = null;

    @SerializedName("repository_url")
    private String repositoryUrl = null;

    @SerializedName("services_credential_user_id")
    private Integer servicesCredentialUserId = null;

    @SerializedName("title")
    private String title = null;

    public V0AppUpdateParams appleCredentialUserId(Integer appleCredentialUserId) {
        this.appleCredentialUserId = appleCredentialUserId;
        return this;
    }

    /**
     * The new apple credential user ID (recommendation: use the UI to set this)
     *
     * @return appleCredentialUserId
     **/

    public Integer getAppleCredentialUserId() {
        return appleCredentialUserId;
    }

    public void setAppleCredentialUserId(Integer appleCredentialUserId) {
        this.appleCredentialUserId = appleCredentialUserId;
    }

    public V0AppUpdateParams appleCredentialUserSlug(String appleCredentialUserSlug) {
        this.appleCredentialUserSlug = appleCredentialUserSlug;
        return this;
    }

    /**
     * The new apple credential user slug (recommendation: use the UI to set this)
     *
     * @return appleCredentialUserSlug
     **/

    public String getAppleCredentialUserSlug() {
        return appleCredentialUserSlug;
    }

    public void setAppleCredentialUserSlug(String appleCredentialUserSlug) {
        this.appleCredentialUserSlug = appleCredentialUserSlug;
    }

    public V0AppUpdateParams defaultBranch(String defaultBranch) {
        this.defaultBranch = defaultBranch;
        return this;
    }

    /**
     * The new default branch for the application.
     *
     * @return defaultBranch
     **/

    public String getDefaultBranch() {
        return defaultBranch;
    }

    public void setDefaultBranch(String defaultBranch) {
        this.defaultBranch = defaultBranch;
    }

    public V0AppUpdateParams isPublic(Boolean isPublic) {
        this.isPublic = isPublic;
        return this;
    }

    /**
     * The new value of whether an application should be publicly visible
     *
     * @return isPublic
     **/

    public Boolean isIsPublic() {
        return isPublic;
    }

    public void setIsPublic(Boolean isPublic) {
        this.isPublic = isPublic;
    }

    public V0AppUpdateParams repositoryUrl(String repositoryUrl) {
        this.repositoryUrl = repositoryUrl;
        return this;
    }

    /**
     * The new repository URL for the application.
     *
     * @return repositoryUrl
     **/

    public String getRepositoryUrl() {
        return repositoryUrl;
    }

    public void setRepositoryUrl(String repositoryUrl) {
        this.repositoryUrl = repositoryUrl;
    }

    public V0AppUpdateParams servicesCredentialUserId(Integer servicesCredentialUserId) {
        this.servicesCredentialUserId = servicesCredentialUserId;
        return this;
    }

    /**
     * The new service credential user ID (recommendation: use the UI to set this)
     *
     * @return servicesCredentialUserId
     **/

    public Integer getServicesCredentialUserId() {
        return servicesCredentialUserId;
    }

    public void setServicesCredentialUserId(Integer servicesCredentialUserId) {
        this.servicesCredentialUserId = servicesCredentialUserId;
    }

    public V0AppUpdateParams title(String title) {
        this.title = title;
        return this;
    }

    /**
     * The new title of the application.
     *
     * @return title
     **/

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V0AppUpdateParams v0AppUpdateParams = (V0AppUpdateParams) o;
        return Objects.equals(this.appleCredentialUserId, v0AppUpdateParams.appleCredentialUserId) &&
                Objects.equals(this.appleCredentialUserSlug, v0AppUpdateParams.appleCredentialUserSlug) &&
                Objects.equals(this.defaultBranch, v0AppUpdateParams.defaultBranch) &&
                Objects.equals(this.isPublic, v0AppUpdateParams.isPublic) &&
                Objects.equals(this.repositoryUrl, v0AppUpdateParams.repositoryUrl) &&
                Objects.equals(this.servicesCredentialUserId, v0AppUpdateParams.servicesCredentialUserId) &&
                Objects.equals(this.title, v0AppUpdateParams.title);
    }

    @Override
    public int hashCode() {
        return Objects.hash(appleCredentialUserId, appleCredentialUserSlug, defaultBranch, isPublic, repositoryUrl, servicesCredentialUserId, title);
    }

    @Override
    public String toString() {

        String sb = "class V0AppUpdateParams {\n"
                + "    appleCredentialUserId: " + toIndentedString(appleCredentialUserId) + "\n"
                + "    appleCredentialUserSlug: " + toIndentedString(appleCredentialUserSlug) + "\n"
                + "    defaultBranch: " + toIndentedString(defaultBranch) + "\n"
                + "    isPublic: " + toIndentedString(isPublic) + "\n"
                + "    repositoryUrl: " + toIndentedString(repositoryUrl) + "\n"
                + "    servicesCredentialUserId: " + toIndentedString(servicesCredentialUserId) + "\n"
                + "    title: " + toIndentedString(title) + "\n"
                + "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
