/*
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * OpenAPI spec version: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.zebrunner.carina.bitrise.client.model;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

/**
 * V0AppNotificationSettingsUpdateResponse
 */

public class V0AppNotificationSettingsUpdateResponse {
    @SerializedName("msg")
    private String msg = null;

    public V0AppNotificationSettingsUpdateResponse msg(String msg) {
        this.msg = msg;
        return this;
    }

    /**
     * Get msg
     *
     * @return msg
     **/

    public String getMsg() {
        return msg;
    }

    public void setMsg(String msg) {
        this.msg = msg;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V0AppNotificationSettingsUpdateResponse v0AppNotificationSettingsUpdateResponse = (V0AppNotificationSettingsUpdateResponse) o;
        return Objects.equals(this.msg, v0AppNotificationSettingsUpdateResponse.msg);
    }

    @Override
    public int hashCode() {
        return Objects.hash(msg);
    }

    @Override
    public String toString() {

        String sb = "class V0AppNotificationSettingsUpdateResponse {\n"
                + "    msg: " + toIndentedString(msg) + "\n"
                + "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
