/*
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * OpenAPI spec version: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.zebrunner.carina.bitrise.client.model;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
/**
 * V0BuildResponseItemModel
 */



public class V0BuildResponseItemModel {
  @SerializedName("abort_reason")
  private NullsString abortReason = null;

  @SerializedName("branch")
  private NullsString branch = null;

  @SerializedName("build_number")
  private Integer buildNumber = null;

  @SerializedName("commit_hash")
  private NullsString commitHash = null;

  @SerializedName("commit_message")
  private NullsString commitMessage = null;

  @SerializedName("commit_view_url")
  private NullsString commitViewUrl = null;

  @SerializedName("credit_cost")
  private NullsInt64 creditCost = null;

  @SerializedName("environment_prepare_finished_at")
  private String environmentPrepareFinishedAt = null;

  @SerializedName("finished_at")
  private String finishedAt = null;

  @SerializedName("is_on_hold")
  private Boolean isOnHold = null;

  @SerializedName("is_processed")
  private Boolean isProcessed = null;

  @SerializedName("is_status_sent")
  private Boolean isStatusSent = null;

  @SerializedName("log_format")
  private String logFormat = null;

  @SerializedName("machine_type_id")
  private NullsString machineTypeId = null;

  @SerializedName("original_build_params")
  private List<Integer> originalBuildParams = null;

  @SerializedName("pipeline_workflow_id")
  private String pipelineWorkflowId = null;

  @SerializedName("pull_request_id")
  private Integer pullRequestId = null;

  @SerializedName("pull_request_target_branch")
  private NullsString pullRequestTargetBranch = null;

  @SerializedName("pull_request_view_url")
  private NullsString pullRequestViewUrl = null;

  @SerializedName("rebuildable")
  private Boolean rebuildable = null;

  @SerializedName("slug")
  private String slug = null;

  @SerializedName("stack_identifier")
  private NullsString stackIdentifier = null;

  @SerializedName("started_on_worker_at")
  private String startedOnWorkerAt = null;

  @SerializedName("status")
  private Integer status = null;

  @SerializedName("status_text")
  private String statusText = null;

  @SerializedName("tag")
  private NullsString tag = null;

  @SerializedName("triggered_at")
  private String triggeredAt = null;

  @SerializedName("triggered_by")
  private NullsString triggeredBy = null;

  @SerializedName("triggered_workflow")
  private String triggeredWorkflow = null;

  public V0BuildResponseItemModel abortReason(NullsString abortReason) {
    this.abortReason = abortReason;
    return this;
  }

   /**
   * Get abortReason
   * @return abortReason
  **/
  
  public NullsString getAbortReason() {
    return abortReason;
  }

  public void setAbortReason(NullsString abortReason) {
    this.abortReason = abortReason;
  }

  public V0BuildResponseItemModel branch(NullsString branch) {
    this.branch = branch;
    return this;
  }

   /**
   * Get branch
   * @return branch
  **/
  
  public NullsString getBranch() {
    return branch;
  }

  public void setBranch(NullsString branch) {
    this.branch = branch;
  }

  public V0BuildResponseItemModel buildNumber(Integer buildNumber) {
    this.buildNumber = buildNumber;
    return this;
  }

   /**
   * Get buildNumber
   * @return buildNumber
  **/
  
  public Integer getBuildNumber() {
    return buildNumber;
  }

  public void setBuildNumber(Integer buildNumber) {
    this.buildNumber = buildNumber;
  }

  public V0BuildResponseItemModel commitHash(NullsString commitHash) {
    this.commitHash = commitHash;
    return this;
  }

   /**
   * Get commitHash
   * @return commitHash
  **/
  
  public NullsString getCommitHash() {
    return commitHash;
  }

  public void setCommitHash(NullsString commitHash) {
    this.commitHash = commitHash;
  }

  public V0BuildResponseItemModel commitMessage(NullsString commitMessage) {
    this.commitMessage = commitMessage;
    return this;
  }

   /**
   * Get commitMessage
   * @return commitMessage
  **/
  
  public NullsString getCommitMessage() {
    return commitMessage;
  }

  public void setCommitMessage(NullsString commitMessage) {
    this.commitMessage = commitMessage;
  }

  public V0BuildResponseItemModel commitViewUrl(NullsString commitViewUrl) {
    this.commitViewUrl = commitViewUrl;
    return this;
  }

   /**
   * Get commitViewUrl
   * @return commitViewUrl
  **/
  
  public NullsString getCommitViewUrl() {
    return commitViewUrl;
  }

  public void setCommitViewUrl(NullsString commitViewUrl) {
    this.commitViewUrl = commitViewUrl;
  }

  public V0BuildResponseItemModel creditCost(NullsInt64 creditCost) {
    this.creditCost = creditCost;
    return this;
  }

   /**
   * Get creditCost
   * @return creditCost
  **/
  
  public NullsInt64 getCreditCost() {
    return creditCost;
  }

  public void setCreditCost(NullsInt64 creditCost) {
    this.creditCost = creditCost;
  }

  public V0BuildResponseItemModel environmentPrepareFinishedAt(String environmentPrepareFinishedAt) {
    this.environmentPrepareFinishedAt = environmentPrepareFinishedAt;
    return this;
  }

   /**
   * Get environmentPrepareFinishedAt
   * @return environmentPrepareFinishedAt
  **/
  
  public String getEnvironmentPrepareFinishedAt() {
    return environmentPrepareFinishedAt;
  }

  public void setEnvironmentPrepareFinishedAt(String environmentPrepareFinishedAt) {
    this.environmentPrepareFinishedAt = environmentPrepareFinishedAt;
  }

  public V0BuildResponseItemModel finishedAt(String finishedAt) {
    this.finishedAt = finishedAt;
    return this;
  }

   /**
   * Get finishedAt
   * @return finishedAt
  **/
  
  public String getFinishedAt() {
    return finishedAt;
  }

  public void setFinishedAt(String finishedAt) {
    this.finishedAt = finishedAt;
  }

  public V0BuildResponseItemModel isOnHold(Boolean isOnHold) {
    this.isOnHold = isOnHold;
    return this;
  }

   /**
   * Get isOnHold
   * @return isOnHold
  **/
  
  public Boolean isIsOnHold() {
    return isOnHold;
  }

  public void setIsOnHold(Boolean isOnHold) {
    this.isOnHold = isOnHold;
  }

  public V0BuildResponseItemModel isProcessed(Boolean isProcessed) {
    this.isProcessed = isProcessed;
    return this;
  }

   /**
   * Get isProcessed
   * @return isProcessed
  **/
  
  public Boolean isIsProcessed() {
    return isProcessed;
  }

  public void setIsProcessed(Boolean isProcessed) {
    this.isProcessed = isProcessed;
  }

  public V0BuildResponseItemModel isStatusSent(Boolean isStatusSent) {
    this.isStatusSent = isStatusSent;
    return this;
  }

   /**
   * Get isStatusSent
   * @return isStatusSent
  **/
  
  public Boolean isIsStatusSent() {
    return isStatusSent;
  }

  public void setIsStatusSent(Boolean isStatusSent) {
    this.isStatusSent = isStatusSent;
  }

  public V0BuildResponseItemModel logFormat(String logFormat) {
    this.logFormat = logFormat;
    return this;
  }

   /**
   * Get logFormat
   * @return logFormat
  **/
  
  public String getLogFormat() {
    return logFormat;
  }

  public void setLogFormat(String logFormat) {
    this.logFormat = logFormat;
  }

  public V0BuildResponseItemModel machineTypeId(NullsString machineTypeId) {
    this.machineTypeId = machineTypeId;
    return this;
  }

   /**
   * Get machineTypeId
   * @return machineTypeId
  **/
  
  public NullsString getMachineTypeId() {
    return machineTypeId;
  }

  public void setMachineTypeId(NullsString machineTypeId) {
    this.machineTypeId = machineTypeId;
  }

  public V0BuildResponseItemModel originalBuildParams(List<Integer> originalBuildParams) {
    this.originalBuildParams = originalBuildParams;
    return this;
  }

  public V0BuildResponseItemModel addOriginalBuildParamsItem(Integer originalBuildParamsItem) {
    if (this.originalBuildParams == null) {
      this.originalBuildParams = new ArrayList<Integer>();
    }
    this.originalBuildParams.add(originalBuildParamsItem);
    return this;
  }

   /**
   * Get originalBuildParams
   * @return originalBuildParams
  **/
  
  public List<Integer> getOriginalBuildParams() {
    return originalBuildParams;
  }

  public void setOriginalBuildParams(List<Integer> originalBuildParams) {
    this.originalBuildParams = originalBuildParams;
  }

  public V0BuildResponseItemModel pipelineWorkflowId(String pipelineWorkflowId) {
    this.pipelineWorkflowId = pipelineWorkflowId;
    return this;
  }

   /**
   * Get pipelineWorkflowId
   * @return pipelineWorkflowId
  **/
  
  public String getPipelineWorkflowId() {
    return pipelineWorkflowId;
  }

  public void setPipelineWorkflowId(String pipelineWorkflowId) {
    this.pipelineWorkflowId = pipelineWorkflowId;
  }

  public V0BuildResponseItemModel pullRequestId(Integer pullRequestId) {
    this.pullRequestId = pullRequestId;
    return this;
  }

   /**
   * Get pullRequestId
   * @return pullRequestId
  **/
  
  public Integer getPullRequestId() {
    return pullRequestId;
  }

  public void setPullRequestId(Integer pullRequestId) {
    this.pullRequestId = pullRequestId;
  }

  public V0BuildResponseItemModel pullRequestTargetBranch(NullsString pullRequestTargetBranch) {
    this.pullRequestTargetBranch = pullRequestTargetBranch;
    return this;
  }

   /**
   * Get pullRequestTargetBranch
   * @return pullRequestTargetBranch
  **/
  
  public NullsString getPullRequestTargetBranch() {
    return pullRequestTargetBranch;
  }

  public void setPullRequestTargetBranch(NullsString pullRequestTargetBranch) {
    this.pullRequestTargetBranch = pullRequestTargetBranch;
  }

  public V0BuildResponseItemModel pullRequestViewUrl(NullsString pullRequestViewUrl) {
    this.pullRequestViewUrl = pullRequestViewUrl;
    return this;
  }

   /**
   * Get pullRequestViewUrl
   * @return pullRequestViewUrl
  **/
  
  public NullsString getPullRequestViewUrl() {
    return pullRequestViewUrl;
  }

  public void setPullRequestViewUrl(NullsString pullRequestViewUrl) {
    this.pullRequestViewUrl = pullRequestViewUrl;
  }

  public V0BuildResponseItemModel rebuildable(Boolean rebuildable) {
    this.rebuildable = rebuildable;
    return this;
  }

   /**
   * Get rebuildable
   * @return rebuildable
  **/
  
  public Boolean isRebuildable() {
    return rebuildable;
  }

  public void setRebuildable(Boolean rebuildable) {
    this.rebuildable = rebuildable;
  }

  public V0BuildResponseItemModel slug(String slug) {
    this.slug = slug;
    return this;
  }

   /**
   * Get slug
   * @return slug
  **/
  
  public String getSlug() {
    return slug;
  }

  public void setSlug(String slug) {
    this.slug = slug;
  }

  public V0BuildResponseItemModel stackIdentifier(NullsString stackIdentifier) {
    this.stackIdentifier = stackIdentifier;
    return this;
  }

   /**
   * Get stackIdentifier
   * @return stackIdentifier
  **/
  
  public NullsString getStackIdentifier() {
    return stackIdentifier;
  }

  public void setStackIdentifier(NullsString stackIdentifier) {
    this.stackIdentifier = stackIdentifier;
  }

  public V0BuildResponseItemModel startedOnWorkerAt(String startedOnWorkerAt) {
    this.startedOnWorkerAt = startedOnWorkerAt;
    return this;
  }

   /**
   * Get startedOnWorkerAt
   * @return startedOnWorkerAt
  **/
  
  public String getStartedOnWorkerAt() {
    return startedOnWorkerAt;
  }

  public void setStartedOnWorkerAt(String startedOnWorkerAt) {
    this.startedOnWorkerAt = startedOnWorkerAt;
  }

  public V0BuildResponseItemModel status(Integer status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  
  public Integer getStatus() {
    return status;
  }

  public void setStatus(Integer status) {
    this.status = status;
  }

  public V0BuildResponseItemModel statusText(String statusText) {
    this.statusText = statusText;
    return this;
  }

   /**
   * Get statusText
   * @return statusText
  **/
  
  public String getStatusText() {
    return statusText;
  }

  public void setStatusText(String statusText) {
    this.statusText = statusText;
  }

  public V0BuildResponseItemModel tag(NullsString tag) {
    this.tag = tag;
    return this;
  }

   /**
   * Get tag
   * @return tag
  **/
  
  public NullsString getTag() {
    return tag;
  }

  public void setTag(NullsString tag) {
    this.tag = tag;
  }

  public V0BuildResponseItemModel triggeredAt(String triggeredAt) {
    this.triggeredAt = triggeredAt;
    return this;
  }

   /**
   * Get triggeredAt
   * @return triggeredAt
  **/
  
  public String getTriggeredAt() {
    return triggeredAt;
  }

  public void setTriggeredAt(String triggeredAt) {
    this.triggeredAt = triggeredAt;
  }

  public V0BuildResponseItemModel triggeredBy(NullsString triggeredBy) {
    this.triggeredBy = triggeredBy;
    return this;
  }

   /**
   * Get triggeredBy
   * @return triggeredBy
  **/
  
  public NullsString getTriggeredBy() {
    return triggeredBy;
  }

  public void setTriggeredBy(NullsString triggeredBy) {
    this.triggeredBy = triggeredBy;
  }

  public V0BuildResponseItemModel triggeredWorkflow(String triggeredWorkflow) {
    this.triggeredWorkflow = triggeredWorkflow;
    return this;
  }

   /**
   * Get triggeredWorkflow
   * @return triggeredWorkflow
  **/
  
  public String getTriggeredWorkflow() {
    return triggeredWorkflow;
  }

  public void setTriggeredWorkflow(String triggeredWorkflow) {
    this.triggeredWorkflow = triggeredWorkflow;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V0BuildResponseItemModel v0BuildResponseItemModel = (V0BuildResponseItemModel) o;
    return Objects.equals(this.abortReason, v0BuildResponseItemModel.abortReason) &&
        Objects.equals(this.branch, v0BuildResponseItemModel.branch) &&
        Objects.equals(this.buildNumber, v0BuildResponseItemModel.buildNumber) &&
        Objects.equals(this.commitHash, v0BuildResponseItemModel.commitHash) &&
        Objects.equals(this.commitMessage, v0BuildResponseItemModel.commitMessage) &&
        Objects.equals(this.commitViewUrl, v0BuildResponseItemModel.commitViewUrl) &&
        Objects.equals(this.creditCost, v0BuildResponseItemModel.creditCost) &&
        Objects.equals(this.environmentPrepareFinishedAt, v0BuildResponseItemModel.environmentPrepareFinishedAt) &&
        Objects.equals(this.finishedAt, v0BuildResponseItemModel.finishedAt) &&
        Objects.equals(this.isOnHold, v0BuildResponseItemModel.isOnHold) &&
        Objects.equals(this.isProcessed, v0BuildResponseItemModel.isProcessed) &&
        Objects.equals(this.isStatusSent, v0BuildResponseItemModel.isStatusSent) &&
        Objects.equals(this.logFormat, v0BuildResponseItemModel.logFormat) &&
        Objects.equals(this.machineTypeId, v0BuildResponseItemModel.machineTypeId) &&
        Objects.equals(this.originalBuildParams, v0BuildResponseItemModel.originalBuildParams) &&
        Objects.equals(this.pipelineWorkflowId, v0BuildResponseItemModel.pipelineWorkflowId) &&
        Objects.equals(this.pullRequestId, v0BuildResponseItemModel.pullRequestId) &&
        Objects.equals(this.pullRequestTargetBranch, v0BuildResponseItemModel.pullRequestTargetBranch) &&
        Objects.equals(this.pullRequestViewUrl, v0BuildResponseItemModel.pullRequestViewUrl) &&
        Objects.equals(this.rebuildable, v0BuildResponseItemModel.rebuildable) &&
        Objects.equals(this.slug, v0BuildResponseItemModel.slug) &&
        Objects.equals(this.stackIdentifier, v0BuildResponseItemModel.stackIdentifier) &&
        Objects.equals(this.startedOnWorkerAt, v0BuildResponseItemModel.startedOnWorkerAt) &&
        Objects.equals(this.status, v0BuildResponseItemModel.status) &&
        Objects.equals(this.statusText, v0BuildResponseItemModel.statusText) &&
        Objects.equals(this.tag, v0BuildResponseItemModel.tag) &&
        Objects.equals(this.triggeredAt, v0BuildResponseItemModel.triggeredAt) &&
        Objects.equals(this.triggeredBy, v0BuildResponseItemModel.triggeredBy) &&
        Objects.equals(this.triggeredWorkflow, v0BuildResponseItemModel.triggeredWorkflow);
  }

  @Override
  public int hashCode() {
    return Objects.hash(abortReason, branch, buildNumber, commitHash, commitMessage, commitViewUrl, creditCost, environmentPrepareFinishedAt, finishedAt, isOnHold, isProcessed, isStatusSent, logFormat, machineTypeId, originalBuildParams, pipelineWorkflowId, pullRequestId, pullRequestTargetBranch, pullRequestViewUrl, rebuildable, slug, stackIdentifier, startedOnWorkerAt, status, statusText, tag, triggeredAt, triggeredBy, triggeredWorkflow);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V0BuildResponseItemModel {\n");
    
    sb.append("    abortReason: ").append(toIndentedString(abortReason)).append("\n");
    sb.append("    branch: ").append(toIndentedString(branch)).append("\n");
    sb.append("    buildNumber: ").append(toIndentedString(buildNumber)).append("\n");
    sb.append("    commitHash: ").append(toIndentedString(commitHash)).append("\n");
    sb.append("    commitMessage: ").append(toIndentedString(commitMessage)).append("\n");
    sb.append("    commitViewUrl: ").append(toIndentedString(commitViewUrl)).append("\n");
    sb.append("    creditCost: ").append(toIndentedString(creditCost)).append("\n");
    sb.append("    environmentPrepareFinishedAt: ").append(toIndentedString(environmentPrepareFinishedAt)).append("\n");
    sb.append("    finishedAt: ").append(toIndentedString(finishedAt)).append("\n");
    sb.append("    isOnHold: ").append(toIndentedString(isOnHold)).append("\n");
    sb.append("    isProcessed: ").append(toIndentedString(isProcessed)).append("\n");
    sb.append("    isStatusSent: ").append(toIndentedString(isStatusSent)).append("\n");
    sb.append("    logFormat: ").append(toIndentedString(logFormat)).append("\n");
    sb.append("    machineTypeId: ").append(toIndentedString(machineTypeId)).append("\n");
    sb.append("    originalBuildParams: ").append(toIndentedString(originalBuildParams)).append("\n");
    sb.append("    pipelineWorkflowId: ").append(toIndentedString(pipelineWorkflowId)).append("\n");
    sb.append("    pullRequestId: ").append(toIndentedString(pullRequestId)).append("\n");
    sb.append("    pullRequestTargetBranch: ").append(toIndentedString(pullRequestTargetBranch)).append("\n");
    sb.append("    pullRequestViewUrl: ").append(toIndentedString(pullRequestViewUrl)).append("\n");
    sb.append("    rebuildable: ").append(toIndentedString(rebuildable)).append("\n");
    sb.append("    slug: ").append(toIndentedString(slug)).append("\n");
    sb.append("    stackIdentifier: ").append(toIndentedString(stackIdentifier)).append("\n");
    sb.append("    startedOnWorkerAt: ").append(toIndentedString(startedOnWorkerAt)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    statusText: ").append(toIndentedString(statusText)).append("\n");
    sb.append("    tag: ").append(toIndentedString(tag)).append("\n");
    sb.append("    triggeredAt: ").append(toIndentedString(triggeredAt)).append("\n");
    sb.append("    triggeredBy: ").append(toIndentedString(triggeredBy)).append("\n");
    sb.append("    triggeredWorkflow: ").append(toIndentedString(triggeredWorkflow)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
