/*
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * OpenAPI spec version: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.zebrunner.carina.bitrise.client.model;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * V0PipelineListResponseItemModel
 */

public class V0PipelineListResponseItemModel {
    @SerializedName("artifacts")
    private List<PipelineabledomainArtifactMeta> artifacts = null;

    @SerializedName("branch")
    private String branch = null;

    @SerializedName("build_number")
    private Integer buildNumber = null;

    @SerializedName("build_tool_invocations")
    private List<PipelineabledomainBuildToolInvocation> buildToolInvocations = null;

    @SerializedName("commit_hash")
    private String commitHash = null;

    @SerializedName("commit_message")
    private String commitMessage = null;

    @SerializedName("credit_cost")
    private Integer creditCost = null;

    @SerializedName("finished_at")
    private String finishedAt = null;

    @SerializedName("is_on_hold")
    private Boolean isOnHold = null;

    @SerializedName("is_pipeline")
    private Boolean isPipeline = null;

    @SerializedName("is_processed")
    private Boolean isProcessed = null;

    @SerializedName("local_config")
    private PipelineabledomainLocalConfig localConfig = null;

    @SerializedName("pull_request_id")
    private Integer pullRequestId = null;

    @SerializedName("pull_request_target_branch")
    private String pullRequestTargetBranch = null;

    @SerializedName("rebuildable")
    private Boolean rebuildable = null;

    @SerializedName("slug")
    private String slug = null;

    @SerializedName("started_at")
    private String startedAt = null;

    @SerializedName("status")
    private Integer status = null;

    @SerializedName("tag")
    private String tag = null;

    @SerializedName("trigger_params")
    private PipelineabledomainTriggerParams triggerParams = null;

    @SerializedName("triggered_at")
    private String triggeredAt = null;

    @SerializedName("triggered_by")
    private String triggeredBy = null;

    @SerializedName("triggered_workflow")
    private String triggeredWorkflow = null;

    public V0PipelineListResponseItemModel artifacts(List<PipelineabledomainArtifactMeta> artifacts) {
        this.artifacts = artifacts;
        return this;
    }

    public V0PipelineListResponseItemModel addArtifactsItem(PipelineabledomainArtifactMeta artifactsItem) {
        if (this.artifacts == null) {
            this.artifacts = new ArrayList<PipelineabledomainArtifactMeta>();
        }
        this.artifacts.add(artifactsItem);
        return this;
    }

    /**
     * Get artifacts
     *
     * @return artifacts
     **/

    public List<PipelineabledomainArtifactMeta> getArtifacts() {
        return artifacts;
    }

    public void setArtifacts(List<PipelineabledomainArtifactMeta> artifacts) {
        this.artifacts = artifacts;
    }

    public V0PipelineListResponseItemModel branch(String branch) {
        this.branch = branch;
        return this;
    }

    /**
     * Get branch
     *
     * @return branch
     **/

    public String getBranch() {
        return branch;
    }

    public void setBranch(String branch) {
        this.branch = branch;
    }

    public V0PipelineListResponseItemModel buildNumber(Integer buildNumber) {
        this.buildNumber = buildNumber;
        return this;
    }

    /**
     * Get buildNumber
     *
     * @return buildNumber
     **/

    public Integer getBuildNumber() {
        return buildNumber;
    }

    public void setBuildNumber(Integer buildNumber) {
        this.buildNumber = buildNumber;
    }

    public V0PipelineListResponseItemModel buildToolInvocations(List<PipelineabledomainBuildToolInvocation> buildToolInvocations) {
        this.buildToolInvocations = buildToolInvocations;
        return this;
    }

    public V0PipelineListResponseItemModel addBuildToolInvocationsItem(PipelineabledomainBuildToolInvocation buildToolInvocationsItem) {
        if (this.buildToolInvocations == null) {
            this.buildToolInvocations = new ArrayList<PipelineabledomainBuildToolInvocation>();
        }
        this.buildToolInvocations.add(buildToolInvocationsItem);
        return this;
    }

    /**
     * Get buildToolInvocations
     *
     * @return buildToolInvocations
     **/

    public List<PipelineabledomainBuildToolInvocation> getBuildToolInvocations() {
        return buildToolInvocations;
    }

    public void setBuildToolInvocations(List<PipelineabledomainBuildToolInvocation> buildToolInvocations) {
        this.buildToolInvocations = buildToolInvocations;
    }

    public V0PipelineListResponseItemModel commitHash(String commitHash) {
        this.commitHash = commitHash;
        return this;
    }

    /**
     * Get commitHash
     *
     * @return commitHash
     **/

    public String getCommitHash() {
        return commitHash;
    }

    public void setCommitHash(String commitHash) {
        this.commitHash = commitHash;
    }

    public V0PipelineListResponseItemModel commitMessage(String commitMessage) {
        this.commitMessage = commitMessage;
        return this;
    }

    /**
     * Get commitMessage
     *
     * @return commitMessage
     **/

    public String getCommitMessage() {
        return commitMessage;
    }

    public void setCommitMessage(String commitMessage) {
        this.commitMessage = commitMessage;
    }

    public V0PipelineListResponseItemModel creditCost(Integer creditCost) {
        this.creditCost = creditCost;
        return this;
    }

    /**
     * Get creditCost
     *
     * @return creditCost
     **/

    public Integer getCreditCost() {
        return creditCost;
    }

    public void setCreditCost(Integer creditCost) {
        this.creditCost = creditCost;
    }

    public V0PipelineListResponseItemModel finishedAt(String finishedAt) {
        this.finishedAt = finishedAt;
        return this;
    }

    /**
     * Get finishedAt
     *
     * @return finishedAt
     **/

    public String getFinishedAt() {
        return finishedAt;
    }

    public void setFinishedAt(String finishedAt) {
        this.finishedAt = finishedAt;
    }

    public V0PipelineListResponseItemModel isOnHold(Boolean isOnHold) {
        this.isOnHold = isOnHold;
        return this;
    }

    /**
     * Get isOnHold
     *
     * @return isOnHold
     **/

    public Boolean isIsOnHold() {
        return isOnHold;
    }

    public void setIsOnHold(Boolean isOnHold) {
        this.isOnHold = isOnHold;
    }

    public V0PipelineListResponseItemModel isPipeline(Boolean isPipeline) {
        this.isPipeline = isPipeline;
        return this;
    }

    /**
     * Get isPipeline
     *
     * @return isPipeline
     **/

    public Boolean isIsPipeline() {
        return isPipeline;
    }

    public void setIsPipeline(Boolean isPipeline) {
        this.isPipeline = isPipeline;
    }

    public V0PipelineListResponseItemModel isProcessed(Boolean isProcessed) {
        this.isProcessed = isProcessed;
        return this;
    }

    /**
     * Get isProcessed
     *
     * @return isProcessed
     **/

    public Boolean isIsProcessed() {
        return isProcessed;
    }

    public void setIsProcessed(Boolean isProcessed) {
        this.isProcessed = isProcessed;
    }

    public V0PipelineListResponseItemModel localConfig(PipelineabledomainLocalConfig localConfig) {
        this.localConfig = localConfig;
        return this;
    }

    /**
     * Get localConfig
     *
     * @return localConfig
     **/

    public PipelineabledomainLocalConfig getLocalConfig() {
        return localConfig;
    }

    public void setLocalConfig(PipelineabledomainLocalConfig localConfig) {
        this.localConfig = localConfig;
    }

    public V0PipelineListResponseItemModel pullRequestId(Integer pullRequestId) {
        this.pullRequestId = pullRequestId;
        return this;
    }

    /**
     * Get pullRequestId
     *
     * @return pullRequestId
     **/

    public Integer getPullRequestId() {
        return pullRequestId;
    }

    public void setPullRequestId(Integer pullRequestId) {
        this.pullRequestId = pullRequestId;
    }

    public V0PipelineListResponseItemModel pullRequestTargetBranch(String pullRequestTargetBranch) {
        this.pullRequestTargetBranch = pullRequestTargetBranch;
        return this;
    }

    /**
     * Get pullRequestTargetBranch
     *
     * @return pullRequestTargetBranch
     **/

    public String getPullRequestTargetBranch() {
        return pullRequestTargetBranch;
    }

    public void setPullRequestTargetBranch(String pullRequestTargetBranch) {
        this.pullRequestTargetBranch = pullRequestTargetBranch;
    }

    public V0PipelineListResponseItemModel rebuildable(Boolean rebuildable) {
        this.rebuildable = rebuildable;
        return this;
    }

    /**
     * Get rebuildable
     *
     * @return rebuildable
     **/

    public Boolean isRebuildable() {
        return rebuildable;
    }

    public void setRebuildable(Boolean rebuildable) {
        this.rebuildable = rebuildable;
    }

    public V0PipelineListResponseItemModel slug(String slug) {
        this.slug = slug;
        return this;
    }

    /**
     * Get slug
     *
     * @return slug
     **/

    public String getSlug() {
        return slug;
    }

    public void setSlug(String slug) {
        this.slug = slug;
    }

    public V0PipelineListResponseItemModel startedAt(String startedAt) {
        this.startedAt = startedAt;
        return this;
    }

    /**
     * Get startedAt
     *
     * @return startedAt
     **/

    public String getStartedAt() {
        return startedAt;
    }

    public void setStartedAt(String startedAt) {
        this.startedAt = startedAt;
    }

    public V0PipelineListResponseItemModel status(Integer status) {
        this.status = status;
        return this;
    }

    /**
     * Get status
     *
     * @return status
     **/

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public V0PipelineListResponseItemModel tag(String tag) {
        this.tag = tag;
        return this;
    }

    /**
     * Get tag
     *
     * @return tag
     **/

    public String getTag() {
        return tag;
    }

    public void setTag(String tag) {
        this.tag = tag;
    }

    public V0PipelineListResponseItemModel triggerParams(PipelineabledomainTriggerParams triggerParams) {
        this.triggerParams = triggerParams;
        return this;
    }

    /**
     * Get triggerParams
     *
     * @return triggerParams
     **/

    public PipelineabledomainTriggerParams getTriggerParams() {
        return triggerParams;
    }

    public void setTriggerParams(PipelineabledomainTriggerParams triggerParams) {
        this.triggerParams = triggerParams;
    }

    public V0PipelineListResponseItemModel triggeredAt(String triggeredAt) {
        this.triggeredAt = triggeredAt;
        return this;
    }

    /**
     * Get triggeredAt
     *
     * @return triggeredAt
     **/

    public String getTriggeredAt() {
        return triggeredAt;
    }

    public void setTriggeredAt(String triggeredAt) {
        this.triggeredAt = triggeredAt;
    }

    public V0PipelineListResponseItemModel triggeredBy(String triggeredBy) {
        this.triggeredBy = triggeredBy;
        return this;
    }

    /**
     * Get triggeredBy
     *
     * @return triggeredBy
     **/

    public String getTriggeredBy() {
        return triggeredBy;
    }

    public void setTriggeredBy(String triggeredBy) {
        this.triggeredBy = triggeredBy;
    }

    public V0PipelineListResponseItemModel triggeredWorkflow(String triggeredWorkflow) {
        this.triggeredWorkflow = triggeredWorkflow;
        return this;
    }

    /**
     * Get triggeredWorkflow
     *
     * @return triggeredWorkflow
     **/

    public String getTriggeredWorkflow() {
        return triggeredWorkflow;
    }

    public void setTriggeredWorkflow(String triggeredWorkflow) {
        this.triggeredWorkflow = triggeredWorkflow;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V0PipelineListResponseItemModel v0PipelineListResponseItemModel = (V0PipelineListResponseItemModel) o;
        return Objects.equals(this.artifacts, v0PipelineListResponseItemModel.artifacts) &&
                Objects.equals(this.branch, v0PipelineListResponseItemModel.branch) &&
                Objects.equals(this.buildNumber, v0PipelineListResponseItemModel.buildNumber) &&
                Objects.equals(this.buildToolInvocations, v0PipelineListResponseItemModel.buildToolInvocations) &&
                Objects.equals(this.commitHash, v0PipelineListResponseItemModel.commitHash) &&
                Objects.equals(this.commitMessage, v0PipelineListResponseItemModel.commitMessage) &&
                Objects.equals(this.creditCost, v0PipelineListResponseItemModel.creditCost) &&
                Objects.equals(this.finishedAt, v0PipelineListResponseItemModel.finishedAt) &&
                Objects.equals(this.isOnHold, v0PipelineListResponseItemModel.isOnHold) &&
                Objects.equals(this.isPipeline, v0PipelineListResponseItemModel.isPipeline) &&
                Objects.equals(this.isProcessed, v0PipelineListResponseItemModel.isProcessed) &&
                Objects.equals(this.localConfig, v0PipelineListResponseItemModel.localConfig) &&
                Objects.equals(this.pullRequestId, v0PipelineListResponseItemModel.pullRequestId) &&
                Objects.equals(this.pullRequestTargetBranch, v0PipelineListResponseItemModel.pullRequestTargetBranch) &&
                Objects.equals(this.rebuildable, v0PipelineListResponseItemModel.rebuildable) &&
                Objects.equals(this.slug, v0PipelineListResponseItemModel.slug) &&
                Objects.equals(this.startedAt, v0PipelineListResponseItemModel.startedAt) &&
                Objects.equals(this.status, v0PipelineListResponseItemModel.status) &&
                Objects.equals(this.tag, v0PipelineListResponseItemModel.tag) &&
                Objects.equals(this.triggerParams, v0PipelineListResponseItemModel.triggerParams) &&
                Objects.equals(this.triggeredAt, v0PipelineListResponseItemModel.triggeredAt) &&
                Objects.equals(this.triggeredBy, v0PipelineListResponseItemModel.triggeredBy) &&
                Objects.equals(this.triggeredWorkflow, v0PipelineListResponseItemModel.triggeredWorkflow);
    }

    @Override
    public int hashCode() {
        return Objects.hash(artifacts, branch, buildNumber, buildToolInvocations, commitHash, commitMessage, creditCost, finishedAt, isOnHold,
                isPipeline, isProcessed, localConfig, pullRequestId, pullRequestTargetBranch, rebuildable, slug, startedAt, status, tag,
                triggerParams, triggeredAt, triggeredBy, triggeredWorkflow);
    }

    @Override
    public String toString() {

        String sb = "class V0PipelineListResponseItemModel {\n"
                + "    artifacts: " + toIndentedString(artifacts) + "\n"
                + "    branch: " + toIndentedString(branch) + "\n"
                + "    buildNumber: " + toIndentedString(buildNumber) + "\n"
                + "    buildToolInvocations: " + toIndentedString(buildToolInvocations) + "\n"
                + "    commitHash: " + toIndentedString(commitHash) + "\n"
                + "    commitMessage: " + toIndentedString(commitMessage) + "\n"
                + "    creditCost: " + toIndentedString(creditCost) + "\n"
                + "    finishedAt: " + toIndentedString(finishedAt) + "\n"
                + "    isOnHold: " + toIndentedString(isOnHold) + "\n"
                + "    isPipeline: " + toIndentedString(isPipeline) + "\n"
                + "    isProcessed: " + toIndentedString(isProcessed) + "\n"
                + "    localConfig: " + toIndentedString(localConfig) + "\n"
                + "    pullRequestId: " + toIndentedString(pullRequestId) + "\n"
                + "    pullRequestTargetBranch: " + toIndentedString(pullRequestTargetBranch) + "\n"
                + "    rebuildable: " + toIndentedString(rebuildable) + "\n"
                + "    slug: " + toIndentedString(slug) + "\n"
                + "    startedAt: " + toIndentedString(startedAt) + "\n"
                + "    status: " + toIndentedString(status) + "\n"
                + "    tag: " + toIndentedString(tag) + "\n"
                + "    triggerParams: " + toIndentedString(triggerParams) + "\n"
                + "    triggeredAt: " + toIndentedString(triggeredAt) + "\n"
                + "    triggeredBy: " + toIndentedString(triggeredBy) + "\n"
                + "    triggeredWorkflow: " + toIndentedString(triggeredWorkflow) + "\n"
                + "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
