/*
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * OpenAPI spec version: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.zebrunner.carina.bitrise.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * V0PipelineShowResponseModel
 */

public class V0PipelineShowResponseModel {
    @SerializedName("abort_reason")
    private String abortReason = null;

    @SerializedName("app")
    private V0PipelineShowAppResponseModel app = null;

    @SerializedName("attempts")
    private List<V0PipelineShowAttemptResponseModel> attempts = null;

    @SerializedName("credit_cost")
    private Object creditCost = null;

    @SerializedName("current_attempt_id")
    private String currentAttemptId = null;

    @SerializedName("finished_at")
    private String finishedAt = null;

    @SerializedName("id")
    private String id = null;

    @SerializedName("name")
    private String name = null;

    @SerializedName("number_in_app_scope")
    private Integer numberInAppScope = null;

    @SerializedName("put_on_hold_at")
    private Object putOnHoldAt = null;

    @SerializedName("rebuildable")
    private Boolean rebuildable = null;

    @SerializedName("stages")
    private List<V0PipelineShowStageResponseModel> stages = null;

    @SerializedName("started_at")
    private String startedAt = null;
    @SerializedName("status")
    private StatusEnum status = null;
    @SerializedName("trigger_params")
    private V0PipelineShowTriggerParamsResponseModel triggerParams = null;
    @SerializedName("triggered_at")
    private String triggeredAt = null;
    @SerializedName("triggered_by")
    private String triggeredBy = null;

    public V0PipelineShowResponseModel abortReason(String abortReason) {
        this.abortReason = abortReason;
        return this;
    }

    /**
     * Get abortReason
     *
     * @return abortReason
     **/

    public String getAbortReason() {
        return abortReason;
    }

    public void setAbortReason(String abortReason) {
        this.abortReason = abortReason;
    }

    public V0PipelineShowResponseModel app(V0PipelineShowAppResponseModel app) {
        this.app = app;
        return this;
    }

    /**
     * Get app
     *
     * @return app
     **/

    public V0PipelineShowAppResponseModel getApp() {
        return app;
    }

    public void setApp(V0PipelineShowAppResponseModel app) {
        this.app = app;
    }

    public V0PipelineShowResponseModel attempts(List<V0PipelineShowAttemptResponseModel> attempts) {
        this.attempts = attempts;
        return this;
    }

    public V0PipelineShowResponseModel addAttemptsItem(V0PipelineShowAttemptResponseModel attemptsItem) {
        if (this.attempts == null) {
            this.attempts = new ArrayList<V0PipelineShowAttemptResponseModel>();
        }
        this.attempts.add(attemptsItem);
        return this;
    }

    /**
     * Get attempts
     *
     * @return attempts
     **/

    public List<V0PipelineShowAttemptResponseModel> getAttempts() {
        return attempts;
    }

    public void setAttempts(List<V0PipelineShowAttemptResponseModel> attempts) {
        this.attempts = attempts;
    }

    public V0PipelineShowResponseModel creditCost(Object creditCost) {
        this.creditCost = creditCost;
        return this;
    }

    /**
     * Get creditCost
     *
     * @return creditCost
     **/

    public Object getCreditCost() {
        return creditCost;
    }

    public void setCreditCost(Object creditCost) {
        this.creditCost = creditCost;
    }

    public V0PipelineShowResponseModel currentAttemptId(String currentAttemptId) {
        this.currentAttemptId = currentAttemptId;
        return this;
    }

    /**
     * Get currentAttemptId
     *
     * @return currentAttemptId
     **/

    public String getCurrentAttemptId() {
        return currentAttemptId;
    }

    public void setCurrentAttemptId(String currentAttemptId) {
        this.currentAttemptId = currentAttemptId;
    }

    public V0PipelineShowResponseModel finishedAt(String finishedAt) {
        this.finishedAt = finishedAt;
        return this;
    }

    /**
     * Get finishedAt
     *
     * @return finishedAt
     **/

    public String getFinishedAt() {
        return finishedAt;
    }

    public void setFinishedAt(String finishedAt) {
        this.finishedAt = finishedAt;
    }

    public V0PipelineShowResponseModel id(String id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     *
     * @return id
     **/

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public V0PipelineShowResponseModel name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get name
     *
     * @return name
     **/

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public V0PipelineShowResponseModel numberInAppScope(Integer numberInAppScope) {
        this.numberInAppScope = numberInAppScope;
        return this;
    }

    /**
     * Get numberInAppScope
     *
     * @return numberInAppScope
     **/

    public Integer getNumberInAppScope() {
        return numberInAppScope;
    }

    public void setNumberInAppScope(Integer numberInAppScope) {
        this.numberInAppScope = numberInAppScope;
    }

    public V0PipelineShowResponseModel putOnHoldAt(Object putOnHoldAt) {
        this.putOnHoldAt = putOnHoldAt;
        return this;
    }

    /**
     * Get putOnHoldAt
     *
     * @return putOnHoldAt
     **/

    public Object getPutOnHoldAt() {
        return putOnHoldAt;
    }

    public void setPutOnHoldAt(Object putOnHoldAt) {
        this.putOnHoldAt = putOnHoldAt;
    }

    public V0PipelineShowResponseModel rebuildable(Boolean rebuildable) {
        this.rebuildable = rebuildable;
        return this;
    }

    /**
     * Get rebuildable
     *
     * @return rebuildable
     **/

    public Boolean isRebuildable() {
        return rebuildable;
    }

    public void setRebuildable(Boolean rebuildable) {
        this.rebuildable = rebuildable;
    }

    public V0PipelineShowResponseModel stages(List<V0PipelineShowStageResponseModel> stages) {
        this.stages = stages;
        return this;
    }

    public V0PipelineShowResponseModel addStagesItem(V0PipelineShowStageResponseModel stagesItem) {
        if (this.stages == null) {
            this.stages = new ArrayList<V0PipelineShowStageResponseModel>();
        }
        this.stages.add(stagesItem);
        return this;
    }

    /**
     * Get stages
     *
     * @return stages
     **/

    public List<V0PipelineShowStageResponseModel> getStages() {
        return stages;
    }

    public void setStages(List<V0PipelineShowStageResponseModel> stages) {
        this.stages = stages;
    }

    public V0PipelineShowResponseModel startedAt(String startedAt) {
        this.startedAt = startedAt;
        return this;
    }

    /**
     * Get startedAt
     *
     * @return startedAt
     **/

    public String getStartedAt() {
        return startedAt;
    }

    public void setStartedAt(String startedAt) {
        this.startedAt = startedAt;
    }

    public V0PipelineShowResponseModel status(StatusEnum status) {
        this.status = status;
        return this;
    }

    /**
     * Get status
     *
     * @return status
     **/

    public StatusEnum getStatus() {
        return status;
    }

    public void setStatus(StatusEnum status) {
        this.status = status;
    }

    public V0PipelineShowResponseModel triggerParams(V0PipelineShowTriggerParamsResponseModel triggerParams) {
        this.triggerParams = triggerParams;
        return this;
    }

    /**
     * Get triggerParams
     *
     * @return triggerParams
     **/

    public V0PipelineShowTriggerParamsResponseModel getTriggerParams() {
        return triggerParams;
    }

    public void setTriggerParams(V0PipelineShowTriggerParamsResponseModel triggerParams) {
        this.triggerParams = triggerParams;
    }

    public V0PipelineShowResponseModel triggeredAt(String triggeredAt) {
        this.triggeredAt = triggeredAt;
        return this;
    }

    /**
     * Get triggeredAt
     *
     * @return triggeredAt
     **/

    public String getTriggeredAt() {
        return triggeredAt;
    }

    public void setTriggeredAt(String triggeredAt) {
        this.triggeredAt = triggeredAt;
    }

    public V0PipelineShowResponseModel triggeredBy(String triggeredBy) {
        this.triggeredBy = triggeredBy;
        return this;
    }

    /**
     * Get triggeredBy
     *
     * @return triggeredBy
     **/

    public String getTriggeredBy() {
        return triggeredBy;
    }

    public void setTriggeredBy(String triggeredBy) {
        this.triggeredBy = triggeredBy;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V0PipelineShowResponseModel v0PipelineShowResponseModel = (V0PipelineShowResponseModel) o;
        return Objects.equals(this.abortReason, v0PipelineShowResponseModel.abortReason) &&
                Objects.equals(this.app, v0PipelineShowResponseModel.app) &&
                Objects.equals(this.attempts, v0PipelineShowResponseModel.attempts) &&
                Objects.equals(this.creditCost, v0PipelineShowResponseModel.creditCost) &&
                Objects.equals(this.currentAttemptId, v0PipelineShowResponseModel.currentAttemptId) &&
                Objects.equals(this.finishedAt, v0PipelineShowResponseModel.finishedAt) &&
                Objects.equals(this.id, v0PipelineShowResponseModel.id) &&
                Objects.equals(this.name, v0PipelineShowResponseModel.name) &&
                Objects.equals(this.numberInAppScope, v0PipelineShowResponseModel.numberInAppScope) &&
                Objects.equals(this.putOnHoldAt, v0PipelineShowResponseModel.putOnHoldAt) &&
                Objects.equals(this.rebuildable, v0PipelineShowResponseModel.rebuildable) &&
                Objects.equals(this.stages, v0PipelineShowResponseModel.stages) &&
                Objects.equals(this.startedAt, v0PipelineShowResponseModel.startedAt) &&
                Objects.equals(this.status, v0PipelineShowResponseModel.status) &&
                Objects.equals(this.triggerParams, v0PipelineShowResponseModel.triggerParams) &&
                Objects.equals(this.triggeredAt, v0PipelineShowResponseModel.triggeredAt) &&
                Objects.equals(this.triggeredBy, v0PipelineShowResponseModel.triggeredBy);
    }

    @Override
    public int hashCode() {
        return Objects.hash(abortReason, app, attempts, creditCost, currentAttemptId, finishedAt, id, name, numberInAppScope, putOnHoldAt,
                rebuildable, stages, startedAt, status, triggerParams, triggeredAt, triggeredBy);
    }

    @Override
    public String toString() {

        String sb = "class V0PipelineShowResponseModel {\n"
                + "    abortReason: " + toIndentedString(abortReason) + "\n"
                + "    app: " + toIndentedString(app) + "\n"
                + "    attempts: " + toIndentedString(attempts) + "\n"
                + "    creditCost: " + toIndentedString(creditCost) + "\n"
                + "    currentAttemptId: " + toIndentedString(currentAttemptId) + "\n"
                + "    finishedAt: " + toIndentedString(finishedAt) + "\n"
                + "    id: " + toIndentedString(id) + "\n"
                + "    name: " + toIndentedString(name) + "\n"
                + "    numberInAppScope: " + toIndentedString(numberInAppScope) + "\n"
                + "    putOnHoldAt: " + toIndentedString(putOnHoldAt) + "\n"
                + "    rebuildable: " + toIndentedString(rebuildable) + "\n"
                + "    stages: " + toIndentedString(stages) + "\n"
                + "    startedAt: " + toIndentedString(startedAt) + "\n"
                + "    status: " + toIndentedString(status) + "\n"
                + "    triggerParams: " + toIndentedString(triggerParams) + "\n"
                + "    triggeredAt: " + toIndentedString(triggeredAt) + "\n"
                + "    triggeredBy: " + toIndentedString(triggeredBy) + "\n"
                + "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Gets or Sets status
     */
    @JsonAdapter(StatusEnum.Adapter.class)
    public enum StatusEnum {
        @SerializedName("aborted")
        ABORTED("aborted"),
        @SerializedName("failed")
        FAILED("failed"),
        @SerializedName("initializing")
        INITIALIZING("initializing"),
        @SerializedName("on_hold")
        ON_HOLD("on_hold"),
        @SerializedName("running")
        RUNNING("running"),
        @SerializedName("succeeded")
        SUCCEEDED("succeeded"),
        @SerializedName("succeeded_with_abort")
        SUCCEEDED_WITH_ABORT("succeeded_with_abort");

        private final String value;

        StatusEnum(String value) {
            this.value = value;
        }

        public static StatusEnum fromValue(String input) {
            for (StatusEnum b : StatusEnum.values()) {
                if (b.value.equals(input)) {
                    return b;
                }
            }
            return null;
        }

        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        public static class Adapter extends TypeAdapter<StatusEnum> {
            @Override
            public void write(final JsonWriter jsonWriter, final StatusEnum enumeration) throws IOException {
                jsonWriter.value(String.valueOf(enumeration.getValue()));
            }

            @Override
            public StatusEnum read(final JsonReader jsonReader) throws IOException {
                Object value = jsonReader.nextString();
                return StatusEnum.fromValue((String) (value));
            }
        }
    }

}
