/*
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * OpenAPI spec version: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.zebrunner.carina.bitrise.client.model;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

/**
 * V0PipelineListAllResponseItemModel
 */

public class V0PipelineListAllResponseItemModel {
    @SerializedName("branch")
    private String branch = null;

    @SerializedName("build_number")
    private Integer buildNumber = null;

    @SerializedName("commit_hash")
    private String commitHash = null;

    @SerializedName("commit_message")
    private String commitMessage = null;

    @SerializedName("credit_cost")
    private Integer creditCost = null;

    @SerializedName("finished_at")
    private String finishedAt = null;

    @SerializedName("is_on_hold")
    private Boolean isOnHold = null;

    @SerializedName("is_pipeline")
    private Boolean isPipeline = null;

    @SerializedName("is_processed")
    private Boolean isProcessed = null;

    @SerializedName("pull_request_id")
    private Integer pullRequestId = null;

    @SerializedName("pull_request_target_branch")
    private String pullRequestTargetBranch = null;

    @SerializedName("repository")
    private V0AppResponseItemModel repository = null;

    @SerializedName("slug")
    private String slug = null;

    @SerializedName("started_at")
    private String startedAt = null;

    @SerializedName("status")
    private Integer status = null;

    @SerializedName("tag")
    private String tag = null;

    @SerializedName("triggered_at")
    private String triggeredAt = null;

    @SerializedName("triggered_by")
    private String triggeredBy = null;

    @SerializedName("triggered_workflow")
    private String triggeredWorkflow = null;

    public V0PipelineListAllResponseItemModel branch(String branch) {
        this.branch = branch;
        return this;
    }

    /**
     * Get branch
     *
     * @return branch
     **/

    public String getBranch() {
        return branch;
    }

    public void setBranch(String branch) {
        this.branch = branch;
    }

    public V0PipelineListAllResponseItemModel buildNumber(Integer buildNumber) {
        this.buildNumber = buildNumber;
        return this;
    }

    /**
     * Get buildNumber
     *
     * @return buildNumber
     **/

    public Integer getBuildNumber() {
        return buildNumber;
    }

    public void setBuildNumber(Integer buildNumber) {
        this.buildNumber = buildNumber;
    }

    public V0PipelineListAllResponseItemModel commitHash(String commitHash) {
        this.commitHash = commitHash;
        return this;
    }

    /**
     * Get commitHash
     *
     * @return commitHash
     **/

    public String getCommitHash() {
        return commitHash;
    }

    public void setCommitHash(String commitHash) {
        this.commitHash = commitHash;
    }

    public V0PipelineListAllResponseItemModel commitMessage(String commitMessage) {
        this.commitMessage = commitMessage;
        return this;
    }

    /**
     * Get commitMessage
     *
     * @return commitMessage
     **/

    public String getCommitMessage() {
        return commitMessage;
    }

    public void setCommitMessage(String commitMessage) {
        this.commitMessage = commitMessage;
    }

    public V0PipelineListAllResponseItemModel creditCost(Integer creditCost) {
        this.creditCost = creditCost;
        return this;
    }

    /**
     * Get creditCost
     *
     * @return creditCost
     **/

    public Integer getCreditCost() {
        return creditCost;
    }

    public void setCreditCost(Integer creditCost) {
        this.creditCost = creditCost;
    }

    public V0PipelineListAllResponseItemModel finishedAt(String finishedAt) {
        this.finishedAt = finishedAt;
        return this;
    }

    /**
     * Get finishedAt
     *
     * @return finishedAt
     **/

    public String getFinishedAt() {
        return finishedAt;
    }

    public void setFinishedAt(String finishedAt) {
        this.finishedAt = finishedAt;
    }

    public V0PipelineListAllResponseItemModel isOnHold(Boolean isOnHold) {
        this.isOnHold = isOnHold;
        return this;
    }

    /**
     * Get isOnHold
     *
     * @return isOnHold
     **/

    public Boolean isIsOnHold() {
        return isOnHold;
    }

    public void setIsOnHold(Boolean isOnHold) {
        this.isOnHold = isOnHold;
    }

    public V0PipelineListAllResponseItemModel isPipeline(Boolean isPipeline) {
        this.isPipeline = isPipeline;
        return this;
    }

    /**
     * Get isPipeline
     *
     * @return isPipeline
     **/

    public Boolean isIsPipeline() {
        return isPipeline;
    }

    public void setIsPipeline(Boolean isPipeline) {
        this.isPipeline = isPipeline;
    }

    public V0PipelineListAllResponseItemModel isProcessed(Boolean isProcessed) {
        this.isProcessed = isProcessed;
        return this;
    }

    /**
     * Get isProcessed
     *
     * @return isProcessed
     **/

    public Boolean isIsProcessed() {
        return isProcessed;
    }

    public void setIsProcessed(Boolean isProcessed) {
        this.isProcessed = isProcessed;
    }

    public V0PipelineListAllResponseItemModel pullRequestId(Integer pullRequestId) {
        this.pullRequestId = pullRequestId;
        return this;
    }

    /**
     * Get pullRequestId
     *
     * @return pullRequestId
     **/

    public Integer getPullRequestId() {
        return pullRequestId;
    }

    public void setPullRequestId(Integer pullRequestId) {
        this.pullRequestId = pullRequestId;
    }

    public V0PipelineListAllResponseItemModel pullRequestTargetBranch(String pullRequestTargetBranch) {
        this.pullRequestTargetBranch = pullRequestTargetBranch;
        return this;
    }

    /**
     * Get pullRequestTargetBranch
     *
     * @return pullRequestTargetBranch
     **/

    public String getPullRequestTargetBranch() {
        return pullRequestTargetBranch;
    }

    public void setPullRequestTargetBranch(String pullRequestTargetBranch) {
        this.pullRequestTargetBranch = pullRequestTargetBranch;
    }

    public V0PipelineListAllResponseItemModel repository(V0AppResponseItemModel repository) {
        this.repository = repository;
        return this;
    }

    /**
     * Get repository
     *
     * @return repository
     **/

    public V0AppResponseItemModel getRepository() {
        return repository;
    }

    public void setRepository(V0AppResponseItemModel repository) {
        this.repository = repository;
    }

    public V0PipelineListAllResponseItemModel slug(String slug) {
        this.slug = slug;
        return this;
    }

    /**
     * Get slug
     *
     * @return slug
     **/

    public String getSlug() {
        return slug;
    }

    public void setSlug(String slug) {
        this.slug = slug;
    }

    public V0PipelineListAllResponseItemModel startedAt(String startedAt) {
        this.startedAt = startedAt;
        return this;
    }

    /**
     * Get startedAt
     *
     * @return startedAt
     **/

    public String getStartedAt() {
        return startedAt;
    }

    public void setStartedAt(String startedAt) {
        this.startedAt = startedAt;
    }

    public V0PipelineListAllResponseItemModel status(Integer status) {
        this.status = status;
        return this;
    }

    /**
     * Get status
     *
     * @return status
     **/

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public V0PipelineListAllResponseItemModel tag(String tag) {
        this.tag = tag;
        return this;
    }

    /**
     * Get tag
     *
     * @return tag
     **/

    public String getTag() {
        return tag;
    }

    public void setTag(String tag) {
        this.tag = tag;
    }

    public V0PipelineListAllResponseItemModel triggeredAt(String triggeredAt) {
        this.triggeredAt = triggeredAt;
        return this;
    }

    /**
     * Get triggeredAt
     *
     * @return triggeredAt
     **/

    public String getTriggeredAt() {
        return triggeredAt;
    }

    public void setTriggeredAt(String triggeredAt) {
        this.triggeredAt = triggeredAt;
    }

    public V0PipelineListAllResponseItemModel triggeredBy(String triggeredBy) {
        this.triggeredBy = triggeredBy;
        return this;
    }

    /**
     * Get triggeredBy
     *
     * @return triggeredBy
     **/

    public String getTriggeredBy() {
        return triggeredBy;
    }

    public void setTriggeredBy(String triggeredBy) {
        this.triggeredBy = triggeredBy;
    }

    public V0PipelineListAllResponseItemModel triggeredWorkflow(String triggeredWorkflow) {
        this.triggeredWorkflow = triggeredWorkflow;
        return this;
    }

    /**
     * Get triggeredWorkflow
     *
     * @return triggeredWorkflow
     **/

    public String getTriggeredWorkflow() {
        return triggeredWorkflow;
    }

    public void setTriggeredWorkflow(String triggeredWorkflow) {
        this.triggeredWorkflow = triggeredWorkflow;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V0PipelineListAllResponseItemModel v0PipelineListAllResponseItemModel = (V0PipelineListAllResponseItemModel) o;
        return Objects.equals(this.branch, v0PipelineListAllResponseItemModel.branch) &&
                Objects.equals(this.buildNumber, v0PipelineListAllResponseItemModel.buildNumber) &&
                Objects.equals(this.commitHash, v0PipelineListAllResponseItemModel.commitHash) &&
                Objects.equals(this.commitMessage, v0PipelineListAllResponseItemModel.commitMessage) &&
                Objects.equals(this.creditCost, v0PipelineListAllResponseItemModel.creditCost) &&
                Objects.equals(this.finishedAt, v0PipelineListAllResponseItemModel.finishedAt) &&
                Objects.equals(this.isOnHold, v0PipelineListAllResponseItemModel.isOnHold) &&
                Objects.equals(this.isPipeline, v0PipelineListAllResponseItemModel.isPipeline) &&
                Objects.equals(this.isProcessed, v0PipelineListAllResponseItemModel.isProcessed) &&
                Objects.equals(this.pullRequestId, v0PipelineListAllResponseItemModel.pullRequestId) &&
                Objects.equals(this.pullRequestTargetBranch, v0PipelineListAllResponseItemModel.pullRequestTargetBranch) &&
                Objects.equals(this.repository, v0PipelineListAllResponseItemModel.repository) &&
                Objects.equals(this.slug, v0PipelineListAllResponseItemModel.slug) &&
                Objects.equals(this.startedAt, v0PipelineListAllResponseItemModel.startedAt) &&
                Objects.equals(this.status, v0PipelineListAllResponseItemModel.status) &&
                Objects.equals(this.tag, v0PipelineListAllResponseItemModel.tag) &&
                Objects.equals(this.triggeredAt, v0PipelineListAllResponseItemModel.triggeredAt) &&
                Objects.equals(this.triggeredBy, v0PipelineListAllResponseItemModel.triggeredBy) &&
                Objects.equals(this.triggeredWorkflow, v0PipelineListAllResponseItemModel.triggeredWorkflow);
    }

    @Override
    public int hashCode() {
        return Objects.hash(branch, buildNumber, commitHash, commitMessage, creditCost, finishedAt, isOnHold, isPipeline, isProcessed, pullRequestId,
                pullRequestTargetBranch, repository, slug, startedAt, status, tag, triggeredAt, triggeredBy, triggeredWorkflow);
    }

    @Override
    public String toString() {

        String sb = "class V0PipelineListAllResponseItemModel {\n"
                + "    branch: " + toIndentedString(branch) + "\n"
                + "    buildNumber: " + toIndentedString(buildNumber) + "\n"
                + "    commitHash: " + toIndentedString(commitHash) + "\n"
                + "    commitMessage: " + toIndentedString(commitMessage) + "\n"
                + "    creditCost: " + toIndentedString(creditCost) + "\n"
                + "    finishedAt: " + toIndentedString(finishedAt) + "\n"
                + "    isOnHold: " + toIndentedString(isOnHold) + "\n"
                + "    isPipeline: " + toIndentedString(isPipeline) + "\n"
                + "    isProcessed: " + toIndentedString(isProcessed) + "\n"
                + "    pullRequestId: " + toIndentedString(pullRequestId) + "\n"
                + "    pullRequestTargetBranch: " + toIndentedString(pullRequestTargetBranch) + "\n"
                + "    repository: " + toIndentedString(repository) + "\n"
                + "    slug: " + toIndentedString(slug) + "\n"
                + "    startedAt: " + toIndentedString(startedAt) + "\n"
                + "    status: " + toIndentedString(status) + "\n"
                + "    tag: " + toIndentedString(tag) + "\n"
                + "    triggeredAt: " + toIndentedString(triggeredAt) + "\n"
                + "    triggeredBy: " + toIndentedString(triggeredBy) + "\n"
                + "    triggeredWorkflow: " + toIndentedString(triggeredWorkflow) + "\n"
                + "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
