/*
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * OpenAPI spec version: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.zebrunner.carina.bitrise.client.model;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * V0TestDeviceListResponseModel
 */

public class V0TestDeviceListResponseModel {
    @SerializedName("data")
    private List<V0TestDeviceResponseItemModel> data = null;

    public V0TestDeviceListResponseModel data(List<V0TestDeviceResponseItemModel> data) {
        this.data = data;
        return this;
    }

    public V0TestDeviceListResponseModel addDataItem(V0TestDeviceResponseItemModel dataItem) {
        if (this.data == null) {
            this.data = new ArrayList<V0TestDeviceResponseItemModel>();
        }
        this.data.add(dataItem);
        return this;
    }

    /**
     * Get data
     *
     * @return data
     **/

    public List<V0TestDeviceResponseItemModel> getData() {
        return data;
    }

    public void setData(List<V0TestDeviceResponseItemModel> data) {
        this.data = data;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V0TestDeviceListResponseModel v0TestDeviceListResponseModel = (V0TestDeviceListResponseModel) o;
        return Objects.equals(this.data, v0TestDeviceListResponseModel.data);
    }

    @Override
    public int hashCode() {
        return Objects.hash(data);
    }

    @Override
    public String toString() {

        String sb = "class V0TestDeviceListResponseModel {\n"
                + "    data: " + toIndentedString(data) + "\n"
                + "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
