/*
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * OpenAPI spec version: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.zebrunner.carina.bitrise.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import java.io.IOException;

/**
 * Gets or Sets website.BitriseYMLLocation
 */
@JsonAdapter(WebsiteBitriseYMLLocation.Adapter.class)
public enum WebsiteBitriseYMLLocation {
    @SerializedName("bitrise.io")
    BITRISE_IO("bitrise.io"),
    @SerializedName("repository")
    REPOSITORY("repository");

    private final String value;

    WebsiteBitriseYMLLocation(String value) {
        this.value = value;
    }

    public static WebsiteBitriseYMLLocation fromValue(String input) {
        for (WebsiteBitriseYMLLocation b : WebsiteBitriseYMLLocation.values()) {
            if (b.value.equals(input)) {
                return b;
            }
        }
        return null;
    }

    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }

    public static class Adapter extends TypeAdapter<WebsiteBitriseYMLLocation> {
        @Override
        public void write(final JsonWriter jsonWriter, final WebsiteBitriseYMLLocation enumeration) throws IOException {
            jsonWriter.value(String.valueOf(enumeration.getValue()));
        }

        @Override
        public WebsiteBitriseYMLLocation read(final JsonReader jsonReader) throws IOException {
            Object value = jsonReader.nextString();
            return WebsiteBitriseYMLLocation.fromValue((String) (value));
        }
    }
}
